### ISSUE TITLE
Question: is this the official copy of code.google.com/p/pagedown?

### ISSUE THREAD

**Issue by rtfb** [StackExchange/pagedown#87]
I have a dependent package (https://github.com/rtfb/pagedown-editor) and I want to update my references to something that's not as terminally dead as code.google.com. Is this the right place?

**Comment by uftou** [comment]
Not sure what the final answer for this is. However the [official stack exchange github](http://stackexchange.github.io/) page links pagedown to this repo.

**Comment by rtfb** [comment]
Thanks, @uftou, I suppose that will be enough of a confirmation for me. I'm leaving this open for @balpha to decide, though.

**Comment by praveenscience** [comment]
Even I have this question, so let's see what @balpha says?

**Comment by rtfb** [comment]
I originally asked this question on `balpha/pagedown`, and now it redirects to `StackExchange/pagedown`. Given that this is a StackExchange project, under a StackExchange account, I guess this is now as official as it gets. Closing this out.
